version: '3.9'
services:
  note_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note_app
    ports:
      - '3000:3000'
    networks:
      - voidbox_network

networks:
  voidbox_network:
    external: true
